hostname: rancher.localhost

replicas: 1

bootstrapPassword: admin

ingress:
  extraAnnotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/service-upstream: "true"
  ingressClassName: "nginx"
  annotations:
    kubernetes.io/ingress.class: "nginx"
  tls:
    source: rancher
