apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/lezboyer/infra-deployments.git'
    targetRevision: main
    path: kube-prometheus-stack
    helm:
      releaseName: kube-monitor
      valueFiles:
        - values/values-base.yaml
        - values/values-prod.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - Replace=true 
