apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/lezboyer/infra-deployments.git'
    targetRevision: main
    path: nginx-ingress
    helm:
      releaseName: nginx-ingress
      valueFiles:
        - values/values-base.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      