apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: greeting-prod
  namespace: argocd
spec:
  ignoreDifferences:
  - group: ""
    kind: ConfigMap
    name: greeting-frontend
    namespace: prod
    jsonPointers:
      - /data
  project: default
  source:
    repoURL: https://github.com/lezboyer/fullappchart.git
    targetRevision: dev
    path: .
    helm:
      releaseName: greeting
      valueFiles:
        - values/values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    