---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBz9Eu28+p+oQ3qDfoZchBRCxWirWubCNm6QRkuth6HRUAjDa3BZiwtdSF3muU46PFcGBAsiCNGC9tOOOBxd5QB7mVj1tadhPBKJvDAbh25kkLLyuuRAgZy1d44Dy+HUDP4oQ2pY6N/Hxgf/yX4LuB9vgx8Jd/AARcmOvFLia/IH46xOcsxR5PK1zs/pIstxxLITcswKaCKpJ6u4NT0Yn5+96n/Yil7iOviEyAf8O2mE6/D1/tqtKHx1qTfJD/PYomVLtWBmUJTdk0fcZIzIMoyrIkAuENtLko5Mz+J6zcCEyOoT5fmzSDj/JfDM4yPhkaDpcvGJl9r0QabFHyr0r61QnAnCL/T5IMgS+RxB4do8ZTVUQtTSP01gNR+uC6E+5RTkWDvSGaByEAB5Ha394NIznXJ116MZn7l8oReASfIFelZZzYBt8teaDZsIDrsfUTWBJzCgWuuGDlVQeloynq7JE2UgHtajBJzhcxZr5EHPJjFq9VSYmNrHx4uFtII3kgvKZ16oXP3KqOi2sbw4+xrZeWFZ5i+nRnwvo38L0Qk+nHb9jGzDXCvunQ1XnQ9snNXrBWGRVkWJ6LbcAnTapru62Ognh7Kedw+oawKkAsXrO/LSbOBEIpwYYtmvNSk7fZp4y+8rOewcielaulirvBF+VzOxdlqZ0bn6z2ZZ5kJeM+wAYIPWB0pT1IBcSUut4fzsmuckZY=
    admin-user: AgAdTfRhCg4yhUE6K4bkyR8KmiBb4WHnrbkI1wfxDnGJn06X1fVXU6eDSm9Wwo9f3RWMiDt1jWznUPT+BBZentBB57MKIIT9slCDlv42D7KpCE7TXTzpPOBJV8AOY287RrGx9kiCIcNiqdEzL15P6OTX34mGQ0XIdeBUA9GlBeGv5h3MYJ+4Bk2o0kSrS446827A/uYGFqrhbli8yGlBiDZJ7zelt4uJFe8tf0oIipdjdB86bSOB8vAk7ZGMzoVbc2mDrYAjlerQFMmz71vRIxJ1bWnUkH6FmZOqbUNV5Nl+rUWlsy94PTQbtqnWFMtfVl0akQ3c9PshybbUgEpi5hVxB6Si4uEuMR7LYspE0TQEFSw/tBmadOCkB5YL2g9RmtejazX+or6SWflz9ANWFQBQUJ3ZWCUeAGHjSKeEDpR0yFsJtRm9rnEpi6UJnNwwemBbBLP5hI6APOqdksQkjEwmV7XgHK/W274HFpdXCicvgbCHGEE+irteKe47hBKYDxG6vLtsWulK9gyN2+20KhjqwTteOi/6DD8dmyVsntdMvgPZDlpymeed16laOaabfG0wwP7Gus3z6B9K7iffnoJ0Lm9fx4lDgshABIy6utZsMi3Tdgp9IThWbTDkuEDKkE6Yp/iKSZdlG7+d5JsAb3Xl8rtD7HA8Keh5mrj39YwH2V8SOXcU04WIqOyxSKHN8X/2cX7Wghk=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: monitoring
