prometheusOperator:
  enabled: true
prometheus:
  enabled: true
  prometheusSpec:
    retention: 30d
alertmanager:
  enabled: true
grafana:
  enabled: true
  persistence:
    enabled: true
    size: 10Gi
kubeStateMetrics:
  enabled: true
nodeExporter:
  enabled: true