admin:
  existingSecret: grafana-admin-secret
alertmanager:
  enabled: true
prometheus:
  prometheusSpec:
    readinessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 10
      periodSeconds: 10
    livenessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 10
      periodSeconds: 10
syncPolicy:
  syncOptions:
    - Replace=true