prometheus:
  prometheusSpec:
    readinessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 10
      periodSeconds: 10
    livenessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 10
      periodSeconds: 10

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: standard
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi